'use strict'

var chalk = require('chalk');
var db = require('./server/db');
var User = db.model('user');
var Plant = db.model('plant');
var Promise = require('sequelize').Promise;

var seedUsers = function () {

    var users = [
        {
            email: 'testing@fsa.com',
            password: 'password'
        },
        {
            email: 'obama@gmail.com',
            password: 'potus'
        }
    ];

    var creatingUsers = users.map(function (userObj) {
        return User.create(userObj);
    });

    return Promise.all(creatingUsers);

};

var seedPlants = function() {

    let plants = [{
        name: "Basil",
        description: "Basil is a leafy, fragrant annual with a bushy appearance. The most common type of basil is sweet basil; other types include purple basil (less sweet than common basil), Lemon basil (lemon flavor), and Thai basil (licorice flavor). Basil is easy to grow and works well in Italian dishes, but it only grows in the summer, so plan accordingly.",
        sun: 2,
        bestGerminationTemp: 70,
        notes: "Tomatoes make great neighbors for basil plants in the garden. Ensure your outdoor site gets 6-8 hours of full sun daily; soil should be moist and well-drained. Remember to pinch out the flower heads as soon as they appear to make sure that the leaves will continue growing. After the seedlings have their first six leaves, prune to above the second set. Pinch or cut at the base lateral stems to harvest. The best time to harvest is right when the plant starts to bud (before the flowers bloom).",
        goodNeighbors: ["Tomato"],
        isPerennial: false,
        firstHarvest: 35,
        harvestPeriod: 90,
        afterFrost: true,
        howFarBefore: 0,
        howFarAfter: 0,
        width: 12,
        height: 12,
        watering: "Water at least one inch per week.",
        feeding: "n/a",
        diseases: "Variety of bacterial and fungal leaf, stem, and root diseases",
        pests: ["aphids"],
        image: "http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/002/original/02_basil.jpg?1461825930"
    },
    {
        name: "Carrot",
        description: "Carrots are a popular root vegetable that are easy to grow in sandy soil. They are resistant to most pests and diseases, and are a good late season crop that can tolerate frost. Not all carrots are orange; varieties vary in color from purple to white.",
        sun: 2,
        bestGerminationTemp: 60,
        notes: "Carrots are biennial plants. If you leave them in the ground, the tops will flower and produce seeds the second year. Gently mulch to retain moisture, speed germination and block the sun from the roots. Soil should be well drained and loose to prevent forking and stunting of the root growth. Carrots taste much better after a couple of frosts. Following the first hard frost in the fall, cover carrot rows with an 18-inch layer of shredded leaves to preserve them for harvesting later. Carrots are mature at around 2 ½ months and ½ inch in diameter. You may harvest whenever desired maturity is reached. You may leave mature carrots in the soil for storage if the ground will not freeze.",
        goodNeighbors: [],
        isPerennial: true,
        firstHarvest: 70,
        harvestPeriod: 5,
        afterFrost: false,
        howFarBefore: 35,
        howFarAfter: 0,
        width: 12,
        height: 4,
        watering: "Water at least one inch per week.",
        feeding: "n/a",
        diseases: "Aster Yellow Disease will cause shortened and discolored carrot tops and hairy roots. This disease is spread by pests as they feed from plant to plant. Keep weeds down and invest in a control plan for pests such as leafhoppers. This disease has the ability to overwinter.",
        pests: ["wireworms", "flea beetles"],
        image: "http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/002/original/02_basil.jpg?1461825930"
    },
    {
        name: "Lettuce",
        description: "This is a half-hardy vegetable that you can keep growing all season long by planting one small crop at a time. Days to maturity tend to be short. Garden lettuce is far superior, in both taste and vitamin A content, to supermarket brands.",
        sun: 1,
        bestGerminationTemp: 55,
        notes: "Consider planting rows of chives or garlic between your lettuce to control aphids. They act as “barrier plants” for the lettuce. Planning your garden so that lettuce will be in the shade of taller plants, such as tomatoes or sweet corn, in the heat of the summer, may reduce bolting as well. You should be able to sow additional seeds every two weeks for a continuous harvest throughout the growing season. Lettuce should be harvested when full size, but just before maturity. You want it young and tender. Before maturity, you can harvest leaf lettuce by simply removing outer leaves so that the center leaves can continue to grow. Butterhead or romaine types can be harvested by removing the outer leaves, digging up the whole plant or cutting the plant about an inch above the soil surface. A second harvest is often possible this way. Crisphead lettuce is picked when the center is firm. It’s best to harvest in the morning before leaves have been exposed to sun.",
        goodNeighbors: ["Chive", "Garlic", "Tomato", "Sweet Corn"],
        isPerennial: false,
        firstHarvest: 65,
        harvestPeriod: 5,
        afterFrost: false,
        howFarBefore: 7,
        howFarAfter: 0,
        width: 8,
        height: 8,
        watering: "Make sure soil remains moist but is well-drained. Lettuce will tell you when it needs water. Just look at it. If the leaves are wilting, sprinkle them anytime—even in the heat of the day—to cool them off and slow down the transpiration rate.",
        feeding: "n/a",
        diseases: "White Mold",
        pests: ["aphids", "earwigs"],
        image: "http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/003/original/03_lettuce.jpg?1461825932"
    },
    {
        name: "Broccoli",
        description: "Broccoli is a cool-season crop that, like spinach, can be grown in the spring or fall. In fact, you may be able to get a continual harvest throughout both seasons if you time planting correctly. A member of the cabbage family, broccoli is rich in vitamins.",
        sun: 2,
        bestGerminationTemp: 50,
        notes: "Roots are very shallow, do not cultivate. Suffocate weeds with mulch. In terms of timing: Harvest broccoli when the buds of the head are firm and tight before the heads flower. If you see yellow petals, harvest immediately. For best taste, harvest in the morning before the soil heats up. Cut the stalk of the main head at a slant, about 5 to 8 inches below the head. Most varieties have side-shoots that will continue to develop after the main head is harvested. You can harvest from one plant for many weeks, in some cases, from spring to fall, if you’re summer isn’t too hot.",
        goodNeighbors: [""],
        isPerennial: false,
        firstHarvest: 90,
        harvestPeriod: 5,
        afterFrost: true,
        howFarBefore: 0,
        howFarAfter: 60,
        width: 12,
        height: 12,
        watering: "Provide consistent soil moisture with regular watering, especially in drought conditions. Some varieties of broccoli are heat tolerant, but all need moisture. Do not get developing heads wet when watering.",
        feeding: "n/a",
        diseases: "Downy mildew: Yellow patches on leaves are usually caused by moist weather. Keep leaves as dry as possible with good air circulation. Buy resistant varieties. Nitrogen deficiency: If the bottom leaves turn yellow and the problem continues toward the top of the plant, the plants need a high nitrogen (but low phosphorus) fertilizer or bloodmeal. Blood meal is a quick Nitrogen fix for yellowing leaves.",
        pests: ["aphids", "cabbage loopers", "worms"],
        image: "http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/008/original/08_Broccoli.jpg?1461825938"
    },
    {
        name: "Parsnip",
        description: "Parsnips, popular with ancient Greeks and Romans, were brought over to the Americas with the first colonists. Although parsnips are biennials, they are usually grown as an annual vegetable. Parsnips are a hardy, cool-season crop that is best harvested after a hard frost. Parsnips are not only tasty in soups and stews, but can also be enjoyed by themselves.",
        sun: 1,
        bestGerminationTemp: 45,
        notes: "Always sow fresh seed. Parsnips mature in about 16 weeks. Leave your parsnips in the ground for a few frosts but harvest before the ground freezes. If you leave them in the ground for the winter, cover them with a thick layer of mulch and harvest immediately after the ground thaws in the spring.",
        goodNeighbors: [],
        isPerennial: false,
        firstHarvest: 112,
        harvestPeriod: 5,
        afterFrost: false,
        howFarBefore: 21,
        howFarAfter: 0,
        width: 5,
        height: 5,
        watering: "Water during the summer if rainfall is less than 1 inch per week.",
        feeding: "Always keep the beds free of weeds.",
        diseases: "n/a",
        pests: [],
        image: "http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/022/original/22_parsnips.jpg?1461825963"
    },
    {
        name: "Brussel Sprout",
        description: "Brussels Sprouts are a member of the cabbage family, and an excellent source of protein and vitamins. They have a long growing season, and are generally more successful when grown for a fall harvest, as they only increase in flavor after a light frost or two.",
        sun: 1,
        bestGerminationTemp: 50,
        notes: "While starting seeds indoors is recommended, you may also direct sow seeds 4 months before the first fall frost. You may also have luck finding seedlings at a nursery. Thin plants to 12-24 inches apart when they reach 6 inches tall. Mulch will also help to keep soil temperatures down. Harvest sprouts from the bottom of the stalk when they reach about 1 inch in diameter. Do not wash the sprouts before storing them, only right before use.",
        goodNeighbors: [],
        isPerennial: false,
        firstHarvest: 90,
        harvestPeriod: 5,
        afterFrost: false,
        howFarBefore: 14,
        howFarAfter: 0,
        width: 3,
        height: 3,
        watering: "Mulch to retain moisture and keep the soil temperature cool. Do not cultivate, roots are shallow and susceptible to damage. Protect the plant by mulching with straw or providing a cover if you plan to harvest into the winter.",
        feeding: "n/a",
        diseases: "Clubroot, Downy Mildew, White Mold",
        pests: ["aphids", "flea beetles"],
        image: "http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/009/original/09_brussels_sprouts.jpg?1461825940"
    },
    {
        name: "Cabbage",
        description: "Cabbage is a hardy, leafy vegetable full of vitamins. It can be difficult to grow; it only likes cool temperatures, and it can be a magnet for some type of pests. By planning your growing season and providing diligent care, you may have two successful crops in one year, both spring and fall. Many varieties are available to suit both your growing conditions and taste preferences.",
        sun: 2,
        bestGerminationTemp: 65,
        notes: "Best results are achieved when seeds are started indoors a few weeks before the last spring frost and transplanted outside at around 4 weeks old",
        goodNeighbors: [],
        isPerennial: false,
        firstHarvest: 70,
        harvestPeriod: 5,
        afterFrost: true,
        howFarBefore: 0,
        howFarAfter: 0,
        width: 12,
        height: 12,
        watering: "Keep soil moist with mulch and water 2 inches per week. Mulch thickly to retain regulate soil temperature.",
        feeding: "n/a",
        diseases: "Splitting",
        pests: ["cabbageworms", "aphids", "flea beetles"],
        image: "http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/010/original/10_cabbage.jpg?1461825941"

    },
    {
        name: "Cucumber",
        description: "Cucumbers are a warm-season vegetable planted outside in the ground no earlier than 2 weeks after last spring frost date. Most varieties will grow in any amount of space, thanks to the plant's ability to climb. The most common varieties of slicing cucumbers have sprawling vines with large green leaves and curling tendrils. The growth of these plants is fast, and the crop yield is abundant if you care for them properly.",
        sun: 2,
        bestGerminationTemp: 65,
        notes: "A trellis might be a good idea if you want the vine to climb, or if you have limited space. Trellising also protects the fruit from damage from lying on the moist ground. Mulch to hold in soil moisture. If you have limited space or would prefer vertical vines, set up trellises early to avoid damage to seedlings and vines. Spray vines with sugar water to attract bees and set more fruit. Harvest regular slicing cucumbers when they about 6 to 8 inches long (slicing varieties). Harvest dills at 4 to 6 inches long and pickles at 2 inches long for pickles. Harvest by cutting or pinching at the base of the fruit. Cucumbers are best picked before they seeds become hard and are eaten when immature. Do not let them get yellow. A cucumber is of highest quality when it is uniformly green, firm and crisp. At peak harvesting time, you should be picking cucumbers every couple of days. Keep them picked. If you don’t, as plants mature, they will stop producing.",
        goodNeighbors: [],
        isPerennial: false,
        firstHarvest: 65,
        harvestPeriod: 90,
        afterFrost: true,
        howFarBefore: 0,
        howFarAfter: 14,
        width: 6,
        height: 6,
        watering: "When seedlings emerge, begin to water frequently, and increase to a gallon per week after fruit forms. Water consistently; put your finger in the soil and when it is dry past the first joint of your finger, it is time to water. Inconsistent watering leads to bitter-tasting fruit. Water slowly in the morning or early afternoon, avoding the leaves.",
        feeding: "If you've worked in organic matter into the soil before planting, you may only need to side-dress your plants with compost. Or, if you wish, use a fertilizer from your garden store which is low nitrogen/high potassium and phosphorus formula and apply at planting, 1 week after bloom, and every 3 weeks with liquid food, applying directly to the soil around the plants. Or, you can work a granular fertilizer into the soil. Do not overfertilize or the fruits will get stunted.",
        diseases: "Bacterial Wilt, Mosaic Viruses",
        pests: ["Cucumber Beetles", "Whiteflies"],
        image: "http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/015/original/15_cucumber.jpg?1461825949",
    },
    {
        name: "Sweet Corn",
        description: "Sweet corn is an annual with yellow, white, and bi-colored ears. A long, frost-free growing season is necessary after planting. Sweet corn is wind-pollinated, so it should be planted in blocks, rather than in single rows. Early, mid, and late-season varieties extend the harvest. If you miss the optimal harvest time, corn will go downhill fast as sugars convert to starch.",
        sun: 2,
        bestGerminationTemp: 60,
        notes: "Corn is picky about its soil. Work in compost the fall before planting and let over winter in the soil. Starting seeds indoors is not recommended. Harvest when tassels begin to turn brown and cobs start to swell. Kernels should be full and milky. Pull ears downward and twist to take off stalk.",
        goodNeighbors: [],
        isPerennial: false,
        firstHarvest: 80,
        harvestPeriod: 10,
        afterFrost: true,
        howFarBefore: 0,
        howFarAfter: 14,
        width: 10,
        height: 10,
        watering: "Water well at planting time. Soil must be well drained and able to keep consistent moisture. In dry conditions, be sure to keep corn well watered due to its shallow roots. Water at a rate of 5 gallons per sq yard. Mulch helps reduce evaporation.",
        feeding:  "You may choose to fertilize at planting time, corn is meant to grow rapidly. If you are confident that the soil is adequate, this can be skipped.",
        diseases: "n/a",
        pests: ["Flea Beetles", "Cutworms"],
        image: "http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/016/original/16_sweet_corn.jpg?1461825952"
    },
    {
        name: "Eggplant",
        description: "Eggplants are short-lived perennial vegetables, but are usually cultivated as annuals. Also known as aubergines, eggplants differ mainly in size, shape and color of the fruits. Eggplants are tropical and subtropical, requiring relatively high temperatures. Related crop include tomatoes, potatoes and peppers.",
        sun: 2,
        bestGerminationTemp: 75,
        notes: "Start plants indoors 2 months before the soil warms up or buy nursery transplants just before planting. Pinch out the terminal growing points for a bushier plant. Stake plants over 24 inches tall. Harvest 16 to 24 weeks after sowing when the skin of the fruit is shiny and unwrinkled. Cut the fruit close to the stem, but leaving about an inch of it attached.",
        goodNeighbors: [],
        isPerennial: true,
        firstHarvest: 120,
        harvestPeriod: 5,
        afterFrost: true,
        howFarBefore: 0,
        howFarAfter: 21,
        width: 28,
        height: 28,
        watering: "Water well to where the soil is moist like a rung out sponge.",
        feeding: "Apply a balanced fertilizer or compost every two weeks during the growing season.",
        diseases: "Downy and Powdery Mildew",
        pests: ["Aphids", "Spider Mites", "Tomato Hornworms"],
        image: "http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/017/original/17_eggplant.JPG?1461825953"
    },
    {
        name: "Kale",
        description: "Kale is a hardy, cool-season green that is part of the cabbage family. It grows best in the spring and fall and can tolerate all fall frosts. Kale can be used in salads or as a garnish and is rich in minerals and vitamins A and C.",
        sun: 2,
        bestGerminationTemp: 65,
        notes: "Mulch the soil heavily after the first hard freeze; the plants may continue to produce leaves throughout the winter. Kale is ready to harvest when the leaves are about the size of your hand. Pick about one fistful of leaves per harvest. Avoid picking the terminal bud (found at the top center of the plant) because this will help to keep the plant productive. The small, tender leaves can be eaten uncooked and used in salads.",
        goodNeighbors: [],
        isPerennial: false,
        firstHarvest: 55,
        harvestPeriod: 100,
        afterFrost: true,
        howFarBefore: 0,
        howFarAfter: 14,
        width: 10,
        height: 10,
        watering: "Water the plants regularly but be sure not to overwater them.",
        feeding: "n/a",
        diseases: "n/a",
        pests: ["Cabbageworms", "Flea beetles", "Aphids"],
        image: "http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/020/original/20_kale.jpg?1461825957"
    },
    {
        name: "Onion",
        description: "Onions are a cold-season crop, easy to grow because of their hardiness. We recommend using onion sets, which can be planted without worry of frost damage and have a higher success rate than direct seed or transplants. Onions grow well on raised beds or raised rows at least 4 inches high.",
        sun: 2,
        isPerennial: false,
        bestGerminationTemp: 30,
        notes: "Select a location with full sun where your onions won't be shaded by other plants. Soil needs to be well-drained, loose, and rich in nitrogen; compact soil affects bulb development. Make sure soil is well-drained. Mulch will help retain moisture and stifle weeds. Cut or pull any onions that send up flower stalks; this means that the onions have “bolted” and are done. When onions start to mature, the tops become yellow and begin to fall over. At that point, bend the tops down or even stomp on them to speed the final ripening process. When tops are brown, pull the onions. Be sure to harvest in late summer, before cool weather. Mature onions may spoil in fall weather.",
        goodNeighbors: [],
        firstHarvest: 160,
        harvestPeriod: 14,
        afterFrost: false,
        howFarBefore: 21,
        howFarAfter: 0,
        width: 4,
        height: 12,
        watering: "Generally, onions do not need consistent watering if mulch is used. About one inch of water per week (including rain water) is sufficient. If you want sweeter onions, water more. Onions will look healthy even if they are bone dry, be sure to water during drought conditions.",
        feeding: "Fertilize every few weeks with nitrogen to get big bulbs. Cease fertilizing when the onions push the soil away and the bulbing process has started. Do not put the soil back around the onions; the bulb needs to emerge above the soil.",
        diseases: "n/a",
        pests: ["Onion Maggots"],
        image: "http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/018/original/18_onion.jpg?1461825955"
    },
    {
        name: "Garlic",
        description: "Garlic is easy to grow and produces numerous bulbs after a long growing season. It is frost tolerant. Beyond its intense flavor and culinary uses, “the stinking rose” is good in the garden as an insect repellent and has been used for centuries as a home remedy.",
        sun: 2,
        isPerennial: false,
        bestGerminationTemp: 0,
        notes: "Do not plant cloves from the grocery store. They may be unsuited varieties for your area, and most are treated to make their shelf life longer, making them harder to grow. Instead, get cloves from a mail order seed company or a local nursery. Ensure soil is well-drained with plenty of organic matter. Select a sunny spot.",
        goodNeighbors: [],
        firstHarvest: 140,
        harvestPeriod: 7,
        afterFrost: false,
        howFarBefore: 21,
        howFarAfter: 0,
        width: 5,
        height: 5,
        watering: "Water every 3 to 5 days during bulbing (mid-May through June).",
        feeding: "Garlic requires adequate levels of nitrogen. Fertilize accordingly, especially if you see yellowing leaves.",
        diseases: "White Rot",
        pests: [],
        image: "http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/019/original/19_garlic.jpg?1461825956"
    },
    {
        name: "Cantaloupe",
        description: "What we commonly refer to as ‘cantaloupe’ is actually not true cantaloupe, rather, a type of muskmelon. (True cantaloupe has a rough, warty rind and is not widely grown or commercially available in the US.) Muskmelons are a heat-loving fruit with a long growing season. Their cultural and growing requirements are very similar to other melons. They have a net-like, tan rind, and sweet orange flesh. The names muskmelon and cantaloupe are used interchangeably. We will use the name cantaloupe for this page to avoid confusion.",
        sun: 2,
        isPerennial: false,
        bestGerminationTemp: 65,
        notes: "Amend soil with compost before planting. Growing the vines in raised rows, known as hills, ensures good drainage and will hold the sun’s heat longer. If you have limited space, vines can be trained to a support such as a trellis. Mulching with black plastic will serve multiple purposes: it will warm the soil, hinder weed growth and keep developing fruits clean. Row covers are a good idea to keep pests at bay. Blossoms require pollination to set fruit, so be kind to the bees! When rinds begin to change from green to tan or yellow, the melon is probably ripe, but be careful not to pick too early. Look for a crack in the stem where it attaches to the fruit. This is a sign of ripeness as well. The fruit should be easy to separate from the vine, but if they fall off by themselves they are usually overripe. Harvest melon when vines are dry, and be careful not to damage them.",
        goodNeighbors: [],
        firstHarvest: 85,
        harvestPeriod: 7,
        afterFrost: true,
        howFarBefore: 0,
        howFarAfter: 14,
        width: 18,
        height: 36,
        watering: "While melon plants are growing, blooming, and setting fruit, they need 1 to 2 inches of water per week. Water in the morning, and try to avoid wetting the leaves. Reduce watering once fruit are growing. Dry weather produces the sweetest melon. If you’ve had an exceptional amount of rainfall during the ripening stage, this could cause the bland fruit.",
        feeding: "Fertilize when vines start growing.",
        diseases: "Fusarium Wilt",
        pests: ["Aphids", "Cucumber Beetles", "Squash Borers"] ,
        image: "http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/021/original/21_cantaloupe.jpg?1461825961"
    },
    {
        name: "Pea",
        description: "Peas are a cool-season crop, now coming in three separate varieties to suit your garden and cooking needs. They are: Pisum savitum, which includes both garden peas (sweet pea, inedible pod) and snow peas (edible flat pod with small peas inside) and Pisum macrocarpon, snap peas (edible pod with full-size peas). They are easy to grow, but with a very limited growing season. Furthermore, they do not stay fresh long after harvest, so enjoy them while you can!",
        sun: 1,
        isPerennial: false,
        bestGerminationTemp: 45,
        notes: "To get the best head start, turn over your pea planting beds in the fall, add compost to the soil, and mulch well. As with other legumes, pea roots will fix nitrogen in the soil, making it available for other plants. For tall and vine varieties, establish poles or a trellis at time of planting. Keep your peas well picked to encourage more pods to develop. Pick peas in the morning after the dew has dried. They are crispiest then. Always use two hands when you pick peas. Secure the vine with one hand and pull the peas off with your other hand.",
        goodNeighbors: [],
        firstHarvest: 70,
        harvestPeriod: 18,
        afterFrost: false,
        howFarBefore: 35,
        howFarAfter: 0,
        width: 3,
        height: 3,
        watering: "Water sparsely unless the plants are wilting. Do not let plants dry out, or no pods will be produced.",
        feeding: "Be sure, too, that you don’t fertilize the soil too much. Peas are especially sensitive to too much nitrogen, but they may like a little bonemeal, for the phosphorus content.",
        diseases: "Fusarium Wilt",
        pests: ["Aphids", "Mexican Bean Beetles"],
        image: "http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/023/original/23_peas.jpg?1461825964"
    },
    {
        name: "Potato",
        description: "This half hardy vegetable is a culinary staple, and yet is overlooked by many backyard gardeners. The taste and texture of home-grown potatoes are far superior to store bought, especially the early varieties. They need a cool climate, and also need to be watched to prevent sunburn. Potatoes can be grown as a winter crop in warmer climate zones.",
        sun: 2,
        isPerennial: false,
        bestGerminationTemp: 45,
        notes: "If you are cutting up potato pieces for planting, do so a 1-2 days ahead of time. This will give them the chance to form a protective layer, both for moisture retention and rot resistance. Potatoes thrive in well-drained, loose soil. Hilling should be done before the potato plants bloom, when the plant is about 6 inches tall. Hoe the dirt up around the base of the plant in order to cover the root as well as to support the plant. Bury them in loose soil. The idea is to keep the potato from getting sunburned, in which case they turn green and will taste bitter. You will need to hill potatoes every couple of weeks to protect your crop. Dig potatoes on a dry day. Dig up gently, being careful not to puncture the tubers. The soil should not be compact, so digging should be easy. New potatoes will be ready for harvest after 10 weeks, usually in early July. You should harvest all of your potatoes once the vines die (usually by late August), or the potatoes may rot.",
        goodNeighbors: [],
        firstHarvest: 100,
        harvestPeriod: 21,
        afterFrost: false,
        howFarBefore: 7,
        howFarAfter: 0,
        width: 12,
        height: 12,
        watering: "Potatoes need consistent moisture, so water regularly when tubers start to form.",
        feeding: "n/a",
        diseases: "Early/Late Blight",
        pests: ["Aphids", "Flea Beetles", "Leaf Hoppers"],
        image: "http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/025/original/25_potatoes.jpg?1461825967"
    },
    {
        name: "Pumpkin",
        description: "Whether you use them for carving or cooking, pumpkins do not disappoint. Note that pumpkins do require a lot of food and a long growing season (generally from 75 to 100 frost-free days) so you need to plant them by late May in northern locations to early July in extremely southern states. Do not plant this tender vegetable until all danger of frost has passed and the soil is warmed as the seedlings will be injured or rot. (See the Almanac.com/Gardening page for frost dates.) That said, pumpkins are easy to maintain if you have the space.",
        sun: 2,
        isPerennial: false,
        bestGerminationTemp: 70,
        notes: "Pick a site with full sun (to light shade) and lots of space for sprawling vines. Vine varieties need 50 to 100 square feet per hill. Pumpkins are big greedy feeders. They prefer very rich soil that is well-drained and not too soggy. Mix lots of compost and aged mature into the planting site before you sow seeds or transplant. Pumpkins do best when the seeds are directly planted in the ground. Use row covers to protect plants early in the season and to prevent insect problems. However, remember to remove covers before flowering to allow pollination by insects! Add mulch around your pumpkins to keep in moisture, suppress weeks, and discourage pests. Remember that pumpkins are tender from planting to harvest. Control weeds with mulch. Do not over-cultivate, or their very shallow roots may be damaged. Pinch off the fuzzy ends of each vine after a few pumpkins have formed. This will stop vine growth so that the plant’s energies are focused on the fruit. Your best bet is to harvest pumpkins when they are mature. They will keep best this way. Do not pick pumpkins off the vine because they have reached your desired size. If you want small pumpkins, buy a small variety. A pumpkin is ripening when its skin turns a deep, solid color (orange for most varieties). When you thumb the pumpkin, the rind will feel hard and it will sound hollow. Press your nail into the pumpkin’s skin; if it resists puncture, it is ripe. To harvest the pumpkin, cut the fruit off the vine carefully with a sharp knife or pruners; do not tear. Be sure not to cut too close to the pumpkin; a liberal amount of stem (3 to 4 inches) will increase the pumpkin’s keeping time.",
        goodNeighbors: [],
        firstHarvest: 120,
        harvestPeriod: 45,
        afterFrost: true,
        howFarBefore: 0,
        howFarAfter: 14,
        width: 24,
        height: 72,
        watering: "Pumpkins are very thirsty plants and need lots of water. Water one inch per week. Water deeply, especially during fruit set. When watering: Try to keep foliage and fruit dry unless it’s a sunny day. Dampness will make rot more likely.",
        feeding: "Pumpkins are HEAVY feeders. Regular treatments of manure or compost mixed with water will sustain good growth.",
        diseases: "Powdery Mildew, Anthracnose",
        pests: ["Aphids", "Squash Borers"],
        image: "http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/026/original/26_pumpkin.jpg?1461825970"
    },
    {
        name: "Radishes",
        description: "Radishes are a hardy, cool-season vegetable that can produce many crops each season due to its rapid days to maturity. Radishes can be planted in both the spring and the fall, but growing should be suspended in the warmer months. They are a very easy vegetable to grow.",
        sun: 2,
        bestGerminationTemp: 45,
        notes: "Radishes need sun. If they are planted in too much shade—or even where neighboring vegetable plants shade them—they put all their energy into producing larger leaves. Plant consecutively every two weeks or so while weather is still cool for a continuous harvest of radishes. Plan on a fall planting. You can plant radishes later than any other root crop in late summer or early fall and still get a harvest. Radishes will be ready to harvest quite rapidly, as three weeks after planting for some varieties. Pull at the base of the stem when harvesting.",
        goodNeighbors: [],
        isPerennial: false,
        firstHarvest: 25,
        harvestPeriod: 18,
        afterFrost: true,
        howFarBefore: 35,
        howFarAfter: 0,
        width: 2,
        height: 2,
        watering: "Radishes require well-drained soil with consistent moisture. Keep soil evenly moist but not waterlogged.",
        feeding: "n/a",
        diseases: "Clubroot",
        pests: ["Cabbage Root Maggot"],
        images: "http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/027/original/27_radish.jpg?1461825971"
    },
    {
        name: "Celery",
        description: "Celery is a long-season crop that can be tricky to grow, some might say, the trickiest of all. It likes fertile soil, cool temperatures, and constant moisture. It will not tolerate heat and can be hard to transplant. Summer crops in the north and winter crops in the south make celery a year-round producer. All the work is worth it when you harvest crunchy, green stalks. Celery seeds should always be started indoors for the best success rate, 8 to 10 weeks before the average last frost date for your area. For summer gardeners, a late summer direct sowing is possible. Be sure that temps will stay between 55 and 70ºF throughout growing period. The parts of celery that are harvested are mainly the stalks, which will be above ground. Harvest stalks from the outside in. You may begin harvesting when stalks are about 8 inches tall.",
        sun: 1,
        bestGerminationTemp: 65,
        notes: "The parts of celery that are harvested are mainly the stalks, which will be above ground. Harvest stalks from the outside in. You may begin harvesting when stalks are about 8 inches tall.",
        goodNeighbors: [],
        isPerennial: false,
        firstHarvest: 100,
        harvestPeriod: 21,
        afterFrost: false,
        howFarBefore: 0,
        howFarAfter: 0,
        width: 10,
        height: 10,
        watering: "",
        feeding: "n/a",
        diseases: "Fusarium Wilt, Mosaic Virus",
        pests: ["Cutworms", "Aphids", "Whiteflies"],
        images: "http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/012/original/12_celery.jpg?1461825944"
    },
    {
        name: "Chives",
        description: "Chives are a perennial member of the onion family that sport beautiful purple flowers. Chives are cool-season, cold-tolerant perennials that are planted in early spring. Be mindful when planting this herb, as it will take over your garden if the flowers are left to ripen (the flowers scatter the seeds). However, this plant is easy to dig up and move if it overwhelms your garden.",
        sun: 2,
        bestGerminationTemp: 65,
        notes: "Soil needs to be moist, fertile, rich, and well-draining. Before planting, incorporate 4 to 6 inches of well-composted organic matter. Apply 2 to 3 tablespoons of all-purpose fertilizer (16-16-8) per square foot of planting area. Work compost and fertilizer into the soil to a depth of 6 to 8 inches. Harvest chives 30 days after you transplant or 60 days after seeding. Cut the leaves down to the base when harvesting (within 1 to 2 inches of the soil). Harvest 3 to 4 times during the first year. In subsequent years, cut plants back monthly. The chive plant will flower in May or June. (The flowers are edible.)",
        goodNeighbors: [],
        isPerennial: true,
        firstHarvest: 90,
        harvestPeriod: 60,
        afterFrost: false,
        howFarBefore: 14,
        howFarAfter: 0,
        width: 5,
        height: 5,
        watering: "It is important to give chives consistent watering throughout the growing season for high yields. Moisten the soil thoroughly when watering. Use mulch to conserve moisture and keep the weeds down. Minimal care is needed for fully grown plants. After the flowers bloom, be sure to remove them so that the seeds aren't spread throughout your garden. Remember to divide the plants every 3 to 4 years in the spring. Chives are much more productive if divided regularly. Allow divided plants to grow for several weeks before harvesting.",
        feeding: "n/a",
        diseases: "Bulb Rots, White Rot, Rust",
        pests: ["Onion fly"],
        images: "http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/013/original/13_chives.jpg?1461825945"
    },
    {
        name: "Cilantro",
        description: "Coriander/cilantro is a fast-growing, aromatic herb that grows in the cooler weather of spring and fall. This herb is used to flavor many recipes and the entire plant is edible. The leaves are called cilantro and the seeds are called coriander.",
        sun: 1,
        bestGerminationTemp: 60,
        notes: "It is best to choose a sunny site that will allow cilantro to self-seed as it is ought to do. Plant in an herb garden or the corner of a vegetable garden. When the weather gets warm, the plant will quickly finish its life cycle and send up a long stalk which will produce blossoms and later seeds. Little plants will sprout during the season and the next spring. To help prevent weeds, mulch around the plants as soon as they are visible above the soil. You can also till shallowly to help prevent root damage from weeds. Harvest while it is low. Plant cilantro in the spring after the last frost date or in the fall. In the Southwest, a fall planting may last through spring when the weather heats up again. Do not grow in summer heat as the plants will bolt (so it is past harvesting). The leaves that grow on bolted plants tend to be bitter in flavor. When the cilantro grows its stalk, cut off the plant after the seeds drop and let it self-seed. The large leaves can be cut individually from the plants. For the smaller leaves, cut them off 1-½ to 2 inches above the crown. You can also remove the entire plant at once; however, this means that you will not be able to continue harvesting for the rest of the growing season.",
        goodNeighbors: [],
        isPerennial: false,
        firstHarvest: 65,
        harvestPeriod: 60,
        afterFrost: false,
        howFarBefore: 14,
        howFarAfter: 0,
        width: 6,
        height: 12,
        watering: "Water the seedlings regularly throughout the growing season. They require about 1 inch of water per week for best growth. Once the plants are established, they do not need as much water per week. Keep them moist, but be careful not to overwater them.",
        feeding: "Fertilize once or twice during the growing season with nitrogen fertilizer. Apply ¼ cup of fertilizer per 25 feet of row. Be sure not to over-fertilizer the plants.",
        diseases: "Fungal wilt, Mildew",
        pests: ["Aphids"],
        images: "http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/038/original/38_cilantro.jpg?1461825988"
    },
    {
        name: "Mint",
        description: "Mint is a perennial with very fragrant, toothed leaves and tiny purple, pink, or white flowers. It has a fruity, aromatic taste. There are many varieties of mint—all fragrant, whether shiny or fuzzy, smooth or crinkled, bright green or variegated. However, you can always tell a member of the mint family by its square stem. Rolling it between your fingers, you’ll notice a pungent scent and think of candy, sweet teas, or maybe even mint juleps.",
        sun: 1,
        bestGerminationTemp: 70,
        notes: "Mints are vigorous perennials that thrive in light soil with good drainage. In the garden, plant mint near cabbage and tomatoes. Most will tolerate some shade, and the variegated types may require some protection from direct sun. Minimal care is needed for mint. For outdoor plants, use a light mulch. This will help keep the soil moist and keep the leaves clean. Right before flowering, cut the stems 1 inch from the ground. You can harvest one mint plant two or three times in one growing season. You can also just pick the leaves as you need them.",
        goodNeighbors: [],
        isPerennial: true,
        firstHarvest: 90,
        harvestPeriod: 60,
        afterFrost: true,
        howFarBefore: 0,
        howFarAfter: 0,
        width: 14,
        height: 20,
        watering: "Be sure to water regularly to keep the soil evenly moist.",
        feeding: "n/a",
        diseases: "Powdery mildew, Rust, Leaf spot",
        pests: [],
        images: "http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/040/original/40_mint.jpg?1461825991"
    },
    {
        name: "Tomatoes",
        description: "Tomatoes are America’s favorite garden vegetable. (Yes, we technically eat the fruit of the tomato plant, but it's used as a vegetable in eating and cooking and, thus, usually categorized in vegetables.) This vine plant is fairly easy to grow and will produce a bumper crop with proper care. Its uses are versatile, however, tomatoes are susceptible to a range of pests and diseases.",
        sun: 2,
        bestGerminationTemp: 82,
        notes: "Tomatoes can be either determinate(bush) or indeterminate(climbing) varieties. Determinate varieties can be grown without support, and they typically yield all of their fruit in the span of a few weeks. Indeterminate varieties should be staked, trellised, or caged, and pruned for optimal yields. They yield their fruit over a more extended time period. Tomatoes make great neighbors for basil plants in the garden. Indeterminate varieties will need trellised or caged for best growing results. Leave your tomatoes on the vine as long as possible. The perfect tomato for picking will be firm and very red in color, regardless of size, with perhaps some yellow remaining around the stem. A ripe tomato will be only slightly soft. Pick at the base of the stem.",
        goodNeighbors: [],
        isPerennial: false,
        firstHarvest: 80,
        harvestPeriod: 65,
        afterFrost: true,
        howFarBefore: 0,
        howFarAfter: 35,
        width: 18,
        height: 18,
        watering: "Make sure soil remains moist but is well-drained.",
        feeding: "Water seedlings with a high-phosphate fertilizer solution for best results.",
        diseases: "Learn the common tomato diseases in your area and try to select the most resistant varieties. For prevention, use young, healthy transplants, avoid overhead irrigation, rotate crops, and do not handle tobacco or smoke before handling plants. Fungicides can reduce certain diseases when properly selected and applied. Prevent blossom end rot by providing abundant soil calcium and an even supply of soil moisture.",
        pests: ["Flea Beetles", "Tomato hornworms"],
        images: "http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/001/original/01_tomato.jpg?1461825924"
    },
    {
        name: "Parsley",
        description: "Parsley is a biennial plant with bright green, featherlike leaves and is in the same family as dill. This herb is used in soups, sauces, and salads, and it lessens the need for salt in soups. Not only is it the perfect garnish, but also it is healthy; it’s rich in iron and vitamins A and C.",
        sun: 1,
        bestGerminationTemp: 70,
        notes: "Plant parsley near asparagus, corn, and tomatoes in your garden. When the leaf stems have three segments, parsley is ready to be harvested. Cut leaves from the outer portions of the plant whenever you need them. Leave the inner portions of the plant to mature.",
        goodNeighbors: [],
        isPerennial: true,
        firstHarvest: 75,
        harvestPeriod: 49,
        afterFrost: false,
        howFarBefore: 25,
        howFarAfter: 0,
        width: 8,
        height: 8,
        watering: "Throughout the summer, be sure to water the plants evenly.",
        feeding: "n/a",
        diseases: "Stem rot, Leaf spots",
        pests: ["black swallowtail larvae, carrot fly larvae, celery fly larvae"],
        image: "http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/039/original/39_parsley.jpg?1461825990"
    },
    {
        name: "Sage",
        description: "Sage is a hardy perennial with soft, grayish green leaves. Its flower colors vary; they can be purple, pink, blue, or white. Common sage is used most commonly for cooking; it's a classic in stuffing.",
        sun: 2,
        bestGerminationTemp: 65,
        notes: "Sage can grow from seeds, but the best way to grow high-quality sage is from cuttings from an established plant. In the garden, plant near rosemary, cabbage, and carrots, but keep sage away from cucumbers. Prune the heavier, woody stems every spring. During the first year, harvest lightly to ensure that the plant grows fully. After the first year. be sure to leave a few stalks so that the plant can rejuvenate. If fully established, one plant can be harvested up to three times in one season.",
        isPerennial: true,
        firstHarvest: 60,
        harvestPeriod: 60,
        afterFrost: false,
        howFarBefore: 11,
        howFarAfter: 0,
        width: 27,
        height: 27,
        watering: "Be sure to water the young plants regularly until they are fully grown so that they don't dry out.",
        feeding: "n/a",
        diseases: "Rust, Powdery mildew, Stem rot, Fungal leaf spots",
        pests: ["whiteflies", "aphids"],
        image:  "http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/041/original/41_sage.jpg?1461825992"
    },
    {
        name: "Tarragon",
        description: "Tarragon is a perennial herb with long, light green leaves and tiny greenish or yellowish white flowers. For cooking, use French tarragon. Russian tarragon can easily be mistaken for French, but Russian tarragon is coarser and less flavorful than French tarragon. As soon as the plant has four to five leaves, you can start harvesting. Pinch off the leaves or cut them off with scissors. If you have a lot of plants, you can pinch off entire stalks.",
        sun: 1,
        bestGerminationTemp: 65,
        notes: "Tarragon is a good companion to most vegetables in the garden. In order to ensure a season-long fresh supply of dill, continue sowing seeds every few weeks. For an extended harvest, do not allow flowers to grow on the plants. If the soil remains undisturbed throughout the growing season, more dill plants will grow the next season.",
        goodNeighbors: [],
        isPerennial: true,
        firstHarvest: 150,
        harvestPeriod: 30,
        afterFrost: false,
        howFarBefore: 14,
        howFarAfter: 0,
        width: 30,
        height: 30,
        watering: "Be sure to water the young plants regularly until they are fully grown so that they don't dry out.",
        feeding: "n/a",
        diseases: "Many rusts, including white rust, downy mildew, powdery mildew",
        pests: [],
        images: "http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/042/original/42_tarragon.jpg?1461825994"
    },
    {
        name: "Dill",
        description: "Dill is an annual, self-seeding plant with feathery green leaves. It is used most commonly in soups, stews, and for pickling. Dill is easy to grow and attracts beneficial insects to your garden, such as wasps and other predatory insects.",
        sun: 2,
        bestGerminationTemp: 65,
        notes: "In your garden, plant dill next to cabbage or onions, but keep the dill away from carrots. In order to ensure a season-long fresh supply of dill, continue sowing seeds every few weeks. For an extended harvest, do not allow flowers to grow on the plants. If the soil remains undisturbed throughout the growing season, more dill plants will grow the next season. As soon as the plant has four to five leaves, you can start harvesting. Pinch off the leaves or cut them off with scissors. If you have a lot of plants, you can pinch off entire stalks.",
        goodNeighbors: [],
        isPerennial: false,
        firstHarvest: 42,
        harvestPeriod: 60,
        afterFrost: true,
        howFarBefore: 0,
        howFarAfter: 0,
        width: 18,
        height: 18,
        watering: "Water the plants freely during the growing season.",
        feeding: "n/a",
        diseases: "Leaf spot and occasionally a few other types of fungal leaf and root diseases",
        pests: [],
        images: "http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/045/original/45_dill.JPG?1461825998"
    },
    {
        name: "Cauliflower",
        description: "Cauliflower is a cool-season crop and a descendant of the common cabbage best started from transplants. It is more difficult to than its relatives because it does not tolerate the heat or cold as well. For this reason, cauliflower is usually grown commercially. If you plan to attempt growing cauliflower in the home garden, it requires consistently cool temperatures with temperatures in the 60s. Otherwise, it prematurely “button”—form small button-size heads—rather than forming one, nice white head. Note that the cauliflower will start out as a loose head and it takes time for the head to form. Many varieties take at least 75 to 85 days from transplant. Be patient. When the curd (the white head) is about 2 to 3 inches in diameter, tie the outer leaves together over the head with a rubber band, tape, or twine. This is called blanching, and it protects the head from the sun and helps you get that pretty white color. The plants are usually ready for harvest 7 to 12 days after blanching. When the heads are compact, white, and firm, then it is time to harvest them. Ideally, the heads will grow 6 to 8 inches in diameter. Cut the heads off the plant with a large knife. Be sure to leave some of the leaves around the head to keep it protected. If the heads are too small but have started to open up, they will not improve and should be harvested. If the cauliflower has a coarse appearance, it is too mature and should be tossed.",
        sun: 2,
        bestGerminationTemp: 75,
        notes: "Soil needs be very rich in organic matter; add compost to the soil before planting. Fertile soil holds in moisture to prevent heads from 'buttoning.'",
        goodNeighbors: [],
        isPerennial: false,
        firstHarvest: 55,
        harvestPeriod: 5,
        afterFrost: true,
        howFarBefore: 49,
        howFarAfter: 0,
        width: 21,
        height: 30,
        watering: "Cauliflower requires consistent soil moisture. They need 1 to 1.5 inches of water each week; with normal rainfall, this usually requires supplement watering.",
        feeding: "n/a",
        diseases: "Clubroot, black rot",
        pests: ["cabbageworm", "aphids", "harlequin bugs"],
        images: "http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/011/original/11_cauliflower.jpg?1461825943"
    },{
        name: "Beans",
        description: "Pole and bush beans (more commonly called green beans) are a tender vegetable and a great addition to any garden, great eaten fresh off the plant or incorporated into a recipe. Bush beans require less maintenance, so they are easier to grow.",
        sun: 2,
        bestGerminationTemp: 75,
        notes: "Pole beans will grow in a climbing vine and require a trellis or staking. Bush beans will spread up to 2 feet but do not require support. If you like pole beans, an easy support for them is a “cattle panel”—a portable section of wire fence—16 feet long and 5 feet tall. The beans will climb with ease, and you won’t have to get into contorted positions to pick them. Beans are picked at an immature stage, when the seeds inside have not yet fully developed. Look for firm, sizable pods and snap or cut off the plant. Do not tear the plant.",
        goodNeighbors: [],
        isPerennial: false,
        firstHarvest: 14,
        harvestPeriod: 90,
        afterFrost: true,
        howFarBefore: 0,
        howFarAfter: 0,
        width: 3,
        height: 3,
        watering: "Mulch soil to retain moisture; make sure that it is well-drained. Water regularly, from start of pod to set. Water on sunny days so foliage will not remain soaked.",
        feeding: "n/a",
        diseases: "White Mold, mosaic viruses, bean blossoms will drop from the plant if the weather is too hot and too much nitrogen in the soil will prevent pods from setting.",
        pests: ["aphids", "Mexican bean beetles", "Japanese beetles"],
        images: "http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/006/original/06_beans.jpg?1461825935"
    }, {
        name: "Collard Greens",
        description: "Collard Greens are a hardy, cool-season green that are part of the cabbage family. They grow best in the spring and fall and can tolerate all fall frosts.",
        sun: 2,
        bestGerminationTemp: 65,
        notes: "Collards are ready to harvest when the leaves are about the size of your hand. Pick about one fistful of leaves per harvest. Avoid picking the terminal bud (found at the top center of the plant) because this will help to keep the plant productive. The small, tender leaves can be eaten uncooked and used in salads.",
        goodNeighbors: [],
        isPerennial: false,
        firstHarvest: 100,
        harvestPeriod: 90,
        afterFrost: true,
        howFarBefore: 0,
        howFarAfter: 0,
        width: 12,
        height: 12,
        watering: "Water the plants regularly but be sure not to overwater them. Mulch the soil heavily after the first hard freeze; the plants may continue to produce leaves throughout the winter.",
        feeding: "n/a",
        diseases: "",
        pests: ["cabbageworms", "flea beetles", "aphids"],
        images: "http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/014/original/14_collard_greens.jpg?1461825947"
    },{
        name: 'Rhubarb',
        description: 'Rhubarb is a perennial vegetable, though it is generally used as a fruit in desserts and jams. You only eat the stalks, which have a rich tart flavor. The leaves of this plant are poisonous, so be sure that they are not ingested. Rhubarb is easy to grow, but needs cool weather to thrive.',
        sun: 2,
        bestGerminationTemp: 80,
        notes: 'Plant one-year rhubarb crowns in early spring as soon as the ground is workable when the roots are still dormant and before growth begins or plants are just beginning to leaf out. Rhubarb can also be planted in the fall after dormancy has set in. Before planting, eliminate all perennial weeds. Choose a site that is well-drained, fertile, and preferably in full sunlight. It does best where the average temperature falls below 40ºF in the winter and below 75ºF in the summer. Do not harvest any stalks during the first growing season so that your plants can become established. Harvest the stalks when they are 12 to 18 inches long. Usually after 3 years, the harvest period runs 8 to 10 weeks long. If the stalks become thin, stop harvesting; this means the plant\'s food reserves are low. Grab the base of the stalk and pull it away from the plant with a gentle twist. If this doesn\'t work, you can cut the stalk at the base. Be sure the discard of the leaves! Always leave at least 2 stalks per plant to ensure continued production. You may have a bountiful harvest for up to 20 years without having to replace your rhubarb plants. Remove seed stalks as soon as they appear. Dig and split rhubarb roots every 3 to 4 years.',
        goodNeighbors: [],
        isPerennial: true,
        firstHarvest: 730,
        harvestPeriod: 63,
        afterFrost: true,
        howFarBefore: 0,
        howFarAfter: 7,
        width: 48,
        height: 48,
        watering: 'Water your plant well. It needs sufficient moisture during the summer.',
        feeding: 'After the first spring, apply a light sprinkling of a high-nitrogen fertilizer (25-3-3 or 10-6-4) when the ground is thawing or has just thawed, so that the fertilizer will go into the ground and not harm the roots.',
        diseases: 'Crown rot',
        pests: [],
        image: 'http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/028/original/28_rhubarb.jpg?1461825973'
    },
    {
        name: 'Spinach',
        description: 'This super-cold-hardy vegetable is a tender crop that can be planted in very early spring as well as fall and winter. Spinach has similar growing conditions and requirements as lettuce, but it is more versatile in both its nutrition and its ability to be eaten raw or cooked. It is higher in iron, calcium, and vitamins than most cultivated greens, and one of the best sources of vitamins A, B, and C. Select a site with full sun to light shade and well-drained soil',
        sun: 2,
        isPerennial: false,
        bestGerminationTemp: 65,
        notes: 'Spring plantings can be made as soon as the soil can be properly worked. It’s important to seed as soon as you can to give spinach the required 6 weeks of cool weather from seeding to harvest. Soil should not be warmer than 70º F in order for germination. Successive plantings should be made every couple weeks during early spring. Common spinach cannot grow in midsummer. Plant in mid-August for a fall crop, ensuring that soil temps are cool enough.',
        goodNeighbors: [],
        firstHarvest: 42,
        harvestPeriod: 56,
        afterFrost: true,
        howFarBefore: 0,
        howFarAfter: 7,
        width: 4,
        height: 18,
        watering: 'Water regularly.',
        feeding: 'Fertilize only if necessary due to slow growth, or use as a supplement if your soil’s pH is inadequate. Use when plant reaches ⅓ growth.',
        diseases: 'Downy Mildew, Mosaic Virus, Blight',
        pests: ['Leaf Miners'],
        image: 'http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/029/original/29_spinach.JPG?1461825975'
    },
    {
        name: 'Turnip',
        description: 'Turnips are biennials usually grown as annuals. Although turnips are more of a staple in European kitchens, many southern gardeners like to grow them for their greens. Turnips take up to two months to mature. Turnips grow best in a temperate climate but can endure light frost. Fall crops are usually sweeter and more tender than spring crops—and pests are less of a problem.',
        sun: 2,
        bestGerminationTemp: 85,
        notes: 'Keep the beds weed free and mulch heavily. Harvest some turnips very early as greens. Harvest turnips at any size you wish. The small, young turnips are nice and tender. Pull mature turnips before they become woody and before the first frost.',
        goodNeighbors: [],
        isPerennial: false,
        firstHarvest: 40,
        harvestPeriod: 5,
        afterFrost: true,
        howFarBefore: 0,
        howFarAfter: 7,
        width: 12,
        height: 12,
        watering: 'Water at a rate of 1 inch per week to prevent the roots from becoming tough and bitter.',
        feeding: "n/a",
        diseases: 'Powdery Mildew, Downy Mildew',
        pests: ['Root Maggots', 'Flea Beetles'],
        image: 'http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/032/original/32_turnip.jpg?1461825980'
    },
    {
        name: 'Summer Squash',
        description: 'Squash is a seasonal vegetable. It is very susceptible to frost and heat damage, but with proper care it will produce a bumper crop with very few plants. There are many varieties of summer squash to choose from, including zucchini. The main difference between winter and summer varieties is their harvest time; the longer growing period gives winter squash a tougher, inedible skin',
        sun: 2,
        bestGerminationTemp: 60,
        notes: 'Waiting to plant a few seeds in midsummer will help avoid problems from vine borers and other pests and diseases common earlier in the season. Mulch plants to protect shallow roots, discourage weeds, and retain moisture.',
        goodNeighbors: [],
        isPerennial: false,
        firstHarvest: 60,
        harvestPeriod: 10,
        afterFrost: true,
        howFarBefore: 0,
        howFarAfter: 7,
        width: 60,
        height: 60,
        watering: 'For all type of squash, frequent and consistent watering is recommended. Water most diligently when fruits form and throughout their growth period. Water deeply once a week, applying at least one inch of water. Do not water shallowly; the soil needs to be moist 4 inches down.',
        feeding: 'When the first blooms appear, apply a small amount of fertilizer as a side dress application. After harvest begins, fertilize occasionally for vigorous growth and lots of fruits.',
        diseases: 'Blossom End Rot',
        pests: ['Squash Borer', 'Squash Bug', 'Aphids', 'Stink bug'],
        image: 'http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/030/original/30_summer_squash.jpg?1461825976'
    },
    {
        name: 'Chard',
        description: 'Chard is a member of the beet family that does well in both cool and warm temperatures. It can be cooked or used raw in salads and is high in vitamins A and C.',
        sun: 1,
        bestGerminationTemp: 50,
        notes: 'Mulch the plants to help conserve moisture. For the best quality, cut the plants back when they are about 1 foot tall. If the chard plants become overgrown, they lose their flavor. You can start harvesting when the plants are 6 to 8 inches tall. Cut off the outer leaves 1-½ inches above the ground with a sharp knife. If you harvest the leaves carefully, new leaves will grow and provide another harvest.',
        goodNeighbors: [],
        isPerennial: false,
        firstHarvest: 50,
        harvestPeriod: 56,
        afterFrost: false,
        howFarBefore: 17,
        howFarAfter: 0,
        width: 20,
        height: 20,
        watering: 'Water the plants evenly to help them grow better. Water often during dry spells in the summer.',
        feeding: "n/a",
        diseases: "n/a",
        pests: ['Slugs', 'Aphids'],
        image: 'http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/031/original/31_swiss_chard.jpg?1461825978'
    },
    {
        name: 'Watermelon',
        description: 'Everyone seems to love juicy watermelon in the summertime. Native to Africa, melons need warm temperatures (up to 80 degrees during the day) and a long growing season. Gardeners in colder climates can still have success in growing watermelon by starting seeds indoors and choosing short-season varieties.',
        sun: 2,
        bestGerminationTemp: 85,
        notes: 'Watermelon vines are very tender and should not be transplanted until all danger of frost has passed. (To be safe, wait at least two weeks past your last frost date.) If you are in a cooler zone, start seeds indoors about a month before transplanting. Mulching with black plastic will serve multiple purposes: it will warm the soil, hinder weed growth and keep developing fruits clean. Pruning isn\'t necessary, but vine productivity may be improved if you do not allow lateral (side) vines to grow and stick to the main vine. When the plant is young, just cut off the end buds as they form (before the side shoots become vines). You can also pinch off some blossoms to focus the energy on fewer melons (though it\'s a challenge to kill off a potential fruit!). As fruit is ripening, prevent rotting by gently lifting it and putting some cardboard or straw between the fruit and the soil. Watermelons don’t sweeten after they are picked, so harvest time is important. They generally ripen over two weeks so keep you eye on them. Check the tendril. If it\'s green, wait. If it’s half-dead, the watermelon is nearly ripe or ripe. If the tendril is fully dead, it\'s ripe or overripe; it’s not going to get any riper, so you might as well pick! Stems should be cut with a sharp knife close to the fruit.',
        goodNeighbors: [],
        isPerennial: false,
        firstHarvest: 80,
        harvestPeriod: 5,
        afterFrost: true,
        howFarBefore: 0,
        howFarAfter: 14,
        width: 72,
        height: 72,
        watering: 'Watering is very important from planting until fruit begins to form. While melon plants are growing, blooming, and setting fruit, they need 1 to 2 inches of water per week. Keep soil moist but not waterlogged. Water at the vine\'s base in the morning, and try to avoid wetting the leaves and avoid overhead watering. Reduce watering once fruit are growing. Dry weather produces the sweetest melon.',
        feeding: 'If you choose to fertilize (and many do), make sure it\'s deliver more nitrogen than phosphorus and potassium. However, after flowering begins, use a fertilizer with less nitrogen. We like to use liquid seaweed.',
        diseases: 'Aphids, Squash Borers',
        pests: ['Fusarium Wilt'],
        image: 'http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/033/original/33_watermelon.jpg?1461825981'
    },
    {
        name: 'Winter Squash',
        description: 'Squash is a seasonal vegetable. It is very susceptible to frost and heat damage, but with proper care it will produce a bumper crop with very few plants. The main difference between winter and summer varieties is their harvest time; the longer growing period gives winter squash a tougher, inedible skin',
        sun: 2,
        bestGerminationTemp: 60,
        notes: 'The outside planting site needs to receive full sun; the soil should be moist and well-drained, but not soggy. Squash plants are heavy feeders. Work compost and plenty of organic matter into the soil before planting for a rich soil base. Mulch plants to protect shallow roots, discourage weeds, and retain moisture. Harvest winter squash when rind is hard and deep in color, usually late September through October.',
        goodNeighbors: [],
        isPerennial: false,
        firstHarvest: 90,
        harvestPeriod: 14,
        afterFrost: false,
        howFarBefore: 21,
        howFarAfter: 0,
        width: 60,
        height: 60,
        watering: 'For all type of squash, frequent and consistent watering is recommended. Water most diligently when fruits form and throughout their growth period. Water deeply once a week, applying at least one inch of water. Do not water shallowly; the soil needs to be moist 4 inches down.',
        feeding: 'When the first blooms appear, apply a small amount of fertilizer as a side dress application. After harvest begins, fertilize occasionally for vigorous growth and lots of fruits.',
        diseases: 'Blossom End Rot',
        pests: ['Squash Borer', 'Squash Bug', 'Aphids', 'Stink bug'],
        image: 'http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/034/original/34_winter_squash.jpg?1461825982'
    },
    {
        name: 'Thyme',
        description: 'Thyme is a small perennial shrub with lots of branches and light purple to pink flowers. It\'s aromatic and has a pleasant, pungent, clover flavor. There are over fifty varieties used in cooking and gardening. English thyme is used most often in cooking.',
        sun: 2,
        bestGerminationTemp: 70,
        notes:  'It\'s hard to grow thyme from seeds because of slow, uneven germination. It\'s easier to buy the plants or take some cuttings from a friend. Prune the plants back in the spring and summer to contain the growth. You can take some cuttings and plant them indoors in pots, too. If you have cold winters, remember to lightly mulch around the plants after the ground freezes.Throughout the summer, leaves and sprigs can be harvested at any time.',
        goodNeighbors: ['Cabbage'],
        isPerennial: true,
        firstHarvest: 80,
        harvestPeriod: 42,
        afterFrost: false,
        howFarBefore: 3,
        howFarAfter: 0,
        width: 8,
        height: 8,
        watering: 'Water normally and remember to trim the plants.',
        feeding: "n/a",
        diseases: 'Gray Mold, Root Rot',
        pests: [],
        image: 'http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/035/original/35_thyme.JPG?1461825983'
    },
    {
        name: 'Oregano',
        description: 'Oregano is a perennial with rose-purple or white flowers and a taste reminiscent of thyme. Its taste is zesty and strong and is commonly used in Italian dishes. Oregano is a hardy plant and makes a good ground cover.',
        sun: 2,
        bestGerminationTemp: 70,
        notes: 'Oregano loves the sun; ensure your placement has full, strong sun for strong flavor; some folks plant later in the season for assured warm weather. Oregano makes a good companion for any vegetable in the garden. Oregano can easily be started from seeds, though you can also use cuttings from an established plant. To ensure the best-quality plants, thin out plants that are 3 or 4 years old in the early spring. Oregano is self-seeding, so the plants will easily grow back. You can divide the plants in late spring if you want to put one indoors. Harvest the leaves as you need them. The most flavor-filled leaves are found right before the flowers bloom. Harvest using scissors and give the herb a “haircut”.',
        goodNeighbors: [],
        isPerennial: true,
        firstHarvest: 85,
        harvestPeriod: 49,
        afterFrost: false,
        howFarBefore: 56,
        howFarAfter: 0,
        width: 8,
        height: 8,
        watering: 'Oregano doesn\'t need quite as much water as most herbs. As the amount of watering depends on many variables, just water when the soil feels dry to the touch. Remember that it\'s better to water thoroughly and less often. If you have a container, water until the water comes out of the drainage holes in the bottom of the container.',
        feeding: "n/a",
        diseases: 'Root and Stem Rots',
        pests: ['Aphids'],
        image: 'http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/036/original/36_oregano.jpg?1461825985'
    },
    {
        name: 'Rosemary',
        description: 'Rosemary is a perennial evergreen shrub with blue flowers. It is a pungent and distinctive plant with a sweet, resinous flavor. Rosemary is ideal for a rock garden or the top of a dry wall. It is used for poultry, lamb, stews, and soups.',
        sun: 2,
        bestGerminationTemp: 70,
        notes: 'Plant the seeds/cuttings in well-drained soil. After the plant flowers, remember to trim the plant. Prune/harvest regularly so that the plant won\'t get lanky. Prune the stems to use fresh. During the winter, bring a rosemary plant indoors. Harvest using scissors and give the herb a “haircut”.',
        goodNeighbors: ['Cabbage','Carrots', 'Sage', 'Beans'],
        isPerennial: true,
        firstHarvest: 85,
        harvestPeriod: 60,
        afterFrost: true,
        howFarBefore: 0,
        howFarAfter: 14,
        width: 24,
        height: 24,
        watering: 'Water the plants evenly throughout the growing season.',
        feeding: "n/a",
        diseases: 'Bacterial leaf spots, Aerial Blight, Root Rot',
        pests: [],
        image: 'http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/037/original/37_rosemary.jpg?1461825987'
    },
    {
        name: 'Okra',
        description: 'Okra is traditionally a southern U.S. plant that thrives in warm weather. It is easy to grow and use and looks great throughout the growing season due to its beautiful flowers. Okra is also rich in vitamin A and low in calories.',
        sun: 2,
        bestGerminationTemp: 70,
        notes: 'You can also start okra directly in your garden 3 to 4 weeks before the last spring frost date as long as you cover the plants with a cold frame or grow tunnel until the weather warms up. Make sure that the covering is 2 to 3 feet tall so that the plants have room to grow. If you do not start your okra plants early, wait until there is stable warm weather. You can plant okra in the garden when the soil has warmed to 65° to 70°F. Eliminate weeds when the plants are young, then mulch heavily to prevent more weeds from growing. Apply a layer of mulch 4 to 8 inches high. After the first harvest, remove the lower leaves to help speed up production. Harvest the okra when its about 2 to 3 inches long. Harvest it every other day. Cut the stem just above the cap with a knife; if the stem is too hard to cut, the pod is probably too old and should be tossed. Wear gloves and long sleeves when cutting the okra because most varieties are covered with tiny spines that will irritate your skin, unless you have a spineless variety. Do not worry: this irritation will not happen when you eat them.',
        goodNeighbors: [],
        isPerennial: false,
        firstHarvest: 60,
        harvestPeriod: 5,
        afterFrost: false,
        howFarBefore: 28,
        howFarAfter: 0,
        width: 18,
        height: 18,
        watering: 'Keep the plants well watered throughout the summer months; 1 inch of water per week is ideal, but use more if you are in a hot, arid region.',
        feeding: 'Side-dress the plants with rich compost (½ pound per 25 feet of row). You could also apply a balanced liquid fertilizer monthly.',
        diseases: 'Fusarium wilt',
        pests: ['Aphids', 'Corn Earworms', 'Stinkbugs'],
        image: 'http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/043/original/43_okra.JPG?1461825995'
      },
      {
        name: 'Sweet Potato',
        description: 'The sweet potato is a warm-season, spreading vegetable of tropical origin. It is a good choice for a garden because it is easy to grow, is drought- / heat-tolerant, and has few pests or diseases. The sweet potato is also very nutritious and low in calories.',
        sun: 2,
        bestGerminationTemp: 40,
        notes: 'Sweet potatoes are grown from slips, which are sprouts that are grown from stored sweet potatoes. You can buy slips from garden centers, nurseries, or local farmers. You can also grow your own slips to plant in the spring. In November (this is when the best of the new harvest will be out), go to your supermarket and look for unblemished and uncracked medium sweet potatoes. One potato should yield about 12 plants. Hoe the beds occasionally to keep weeds down. Remember to reshape the beds with soil or mulch. For good harvests, do not prune the vines, because they should be vigorous. You can start digging up the potatoes as soon as they are big enough for a meal. The leaves should have started to yellow, but you can leave them in the ground up until the fall frost. Since the roots spread 4 to 6 inches deep in the soil, a spade fork is useful when digging up the potatoes.',
        goodNeighbors: [],
        isPerennial: false,
        firstHarvest: 120,
        harvestPeriod: 14,
        afterFrost: true,
        howFarBefore: 0,
        howFarAfter: 7,
        width: 14,
        height: 14,
        watering: 'Remember to keep the potatoes watered. Deep watering in hot, dry periods will help to increase yields, although if you are planning to store some of the potatoes, do not give the plants extra water late in the season.',
        feeding: 'Sweet Potatoes like high phosphorus fertilizers.',
        diseases: 'Sweet potato scurf, White blister, Fungal leaf rot',
        pests: ['Flea beetles'],
        image: 'http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/044/original/44_sweet_potato.JPG?1461825996'
    },
    {
        name: 'Beets',
        description: 'Beets are a cool season vegetable crop. This root veggie grows quickly and has many different varieties which showcase deep red, yellow or white bulbs of different shapes. They can survive frost and almost freezing temperatures, which makes them a good choice for northern gardeners and an excellent long-season crop.',
        sun: 1,
        bestGerminationTemp: 50,
        notes: 'A soil pH above 5.5–6 is best, otherwise growth will be stunted. Beets are a good indicator of soil pH. Beets require especially good nutrition and a high phosphorus level to germinate. Go easy on nitrogen however, an excess will cause sprawling greens and tiny bulbs beneath the soil. If you like larger bulbs, wait longer before harvesting, but understand they will be tougher and woody. Don’t let greens grow above 6 inches before harvesting. Don’t forget about the tops! Beet greens have a delicious and distinctive flavor, and hold more nutrition than the roots.',
        goodNeighbors: [],
        isPerennial: false,
        firstHarvest: 60,
        harvestPeriod: 7,
        afterFrost: false,
        howFarBefore: 14,
        howFarAfter: 0,
        width: 4,
        height: 4,
        watering: 'Beets need to maintain plenty of moisture',
        feeding: "n/a",
        diseases: "n/a",
        pests: ['Flea Beetles', 'Leaf Hoppers', 'Mexican Bean Beetles'],
        image: 'http://s3.amazonaws.com/harvest-helper-production/plants/images/000/000/007/original/07_beet.jpg?1461825936'
    }];

    var creatingPlants = plants.map(function (plantObj) {
        return Plant.create(plantObj);
    });

    return Promise.all(creatingPlants);
};

db.sync({ force: true })
    .then(function () {
        return seedUsers();
    })
    .then(function() {
        return seedPlants();
    })
    .then(function () {
        console.log(chalk.green('Seed successful!'));
        process.exit(0);
    })
    .catch(function (err) {
        console.error(err);
        process.exit(1);
    });
